LengoAcademy/Controllers/CourseDetailsController.cs
using LengoAcademy.Models;
using LengoAcademy.SpecificReposoitory;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace LengoAcademy.Controllers
{
    public class CourseDetailsController : Controller
    {

        ICourseRepository courseRepository;
        ITopicsRepository topicsRepository;
        ISectiontRepository sectiontRepository;
        IProcessRepository processRepository;

        public CourseDetailsController
            (ICourseRepository _courseRepository,
            ITopicsRepository _topicsRepository,
            ISectiontRepository _sectiontRepository,
            IProcessRepository _processRepository)
        {
            courseRepository = _courseRepository;
            topicsRepository = _topicsRepository;
            sectiontRepository = _sectiontRepository;
            processRepository = _processRepository;
        }
        public  ActionResult Course_Details(int Id)
        {
            VmCourse_Details vm = new VmCourse_Details();
            vm.course = courseRepository.Load(Id);
            vm.liMainTopics = topicsRepository.MainTopics1(Id);
            vm.liSubTopics = topicsRepository.LoadTopicsByCourseID(Id);
            vm.LiSection = sectiontRepository.LoadSectionByCourseID(Id);
            vm.LiProcess = processRepository.LoadProcessByCourseID(Id);
            vm.licourses = courseRepository.LoadPlan_ItemByCourse_ID(Id);
            vm.section = courseRepository.LoadCourseSectionByCourseId(Id);
            return View("Course_Details", vm);
        }
    }
}

LengoAcademy/Controllers/CoursesController.cs
using LengoAcademy.Models;
using LengoAcademy.SpecificReposoitory;
using System;
using System.Web.Mvc;

namespace LengoAcademy.Controllers
{
    public class CoursesController : Controller
    {
        ICategoryRepository categoryRepository;
        ICourseRepository courseRepository;
        public CoursesController(ICategoryRepository _categoryRepository, ICourseRepository _courseRepository)
        {
            categoryRepository = _categoryRepository;
            courseRepository = _courseRepository;
        }
        public ActionResult NewCourses(int Id)
        {
            VmCourses vm = new VmCourses();
            vm.MainLiCategory = categoryRepository.MainCategory();
            vm.LiSubCategoryById = categoryRepository.SubCategory1(Id);
            vm.LiCourse = courseRepository.LoadCoursesBySubCategoriesID(Id);
            return View("NewCourses", vm);
        }
        public ActionResult AllCourses(int Id)
        {
            int MainId = 0;
            if (Id > 0)
            {
                MainId = Id;
                TempData["MainCatId"] = Id;
            }
            else
            {
                MainId = Convert.ToInt32(TempData["MainCatId"]);
                TempData.Keep("MainCatId");
            }
            VmCourses vm = new VmCourses();
            vm.MainLiCategory = categoryRepository.MainCategory();
            vm.LiSubCategoryById = categoryRepository.LoadSubCategoryByID(MainId);
            vm.LiCourse = courseRepository.LoadAllByMainCategoryID(MainId);


            return View("NewCourses", vm);
        }

        public ActionResult LoadAllByDefaultCategory()
        {
            VmCourses vm = new VmCourses();
            vm.MainLiCategory = categoryRepository.MainCategory();
            vm.LiSubCategoryById = categoryRepository.LoadSubCategoryByID(vm.MainLiCategory[0].Id);
            vm.LiCourse = courseRepository.LoadAllByMainCategoryID(vm.MainLiCategory[0].Id);
            TempData["MainCatId"] = vm.MainLiCategory[0].Id;

            return View("NewCourses", vm);
        }
    }
}

LengoAcademy/Controllers/RegisterEnrollController.cs
using LengoAcademy.Domain;
using LengoAcademy.Entity;
using LengoAcademy.Models;
using LengoAcademy.SpecificReposoitory;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace LengoAcademy.Controllers
{
    public class RegisterEnrollController : Controller
    {
        ICourseRepository courseRepository;
        ISectiontRepository sectiontRepository;
        IAccountRepository accountRepository;

        public RegisterEnrollController(
            ICourseRepository _courseRepository,
            ISectiontRepository _sectiontRepository,
            IAccountRepository _accountRepository)
        {
            courseRepository = _courseRepository;
            sectiontRepository = _sectiontRepository;
            accountRepository = _accountRepository;

        }
        public ActionResult Enroll()
        {
            VmEnroll vm = new VmEnroll();
            vm.LiCourse =  courseRepository.LoadAll();
            return View("Enroll", vm);
        }
        public ActionResult FillSections(int Id)
        {
            List<Section> li = sectiontRepository.LoadSectionByCourseID(Id);
            foreach (Section item in li)
            {
                item.StartDate.ToShortDateString();
            }
            return Json(li);
        }

        public ActionResult Save(VmEnroll signUp)
        {
            List<IdentityRole> liRole = accountRepository.GetRoles();
            signUp.liRoles = liRole;
            signUp.LiCourse =  courseRepository.LoadAll();
            var result =  accountRepository.CreateUser(signUp.signUpDTO);
            signUp.signUpDTO = new SignUpDTO();
            return View("DoneEnroll", signUp);
        }
    }
}

LengoAcademy/Views/Courses/NewCourses.cshtml
@using DareAcademy_DataAccess.Entity
@using LengoAcademy.Models
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model VmCourses
@section Head {
    <style type="text/css">
        .swiper-scrollbar .swiper-scrollbar-lock {
            display: block !important;
        }

        .swiper-scrollbar-lock {
            display: block !important;
        }

        .col-lg-4 {
            flex: 0 0 auto;
            width: 49.333333% !important;
        }
    </style>
}
@section Body{
    <main id="main-body-wrapper">
        <!-- Banner Area -->
        <section class="maan-breadcrumb-area overflow-hidden">
            <div class="container-fluid g-0">
                <div class="row">
                    <div class="col-12">
                        <div class="breadcrumb-bg breadcrumb-bg1" data-background="assets/img/banner/banner3.svg">
                            <div class="row">
                                <div class="col-12">
                                    <div class="maan-breadcrumb-content text-center">
                                        <h2>Development Course</h2>
                                        <nav aria-label="breadcrumb">
                                            <ol class="breadcrumb justify-content-center">
                                                <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                                                @*                                                <li class="breadcrumb-item"><a routerLink="/course">Course</a></li>
                                                *@
                                                <li class="breadcrumb-item active" aria-current="page">
                                                    Development
                                                    Course
                                                </li>
                                            </ol>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Banner Area -->
        <section class="maan-lms-popular-category-section ">
            <div class="container-fluid">
                <div class="mls-popular-category-wrapper maan-section-padding">
                    <!-- <img src="assets/img/new-home/shape1.png" alt="" class="shape1"> -->
                    <img src="~/assets/img/new-home/shape2.png" alt="" class="shape2">
                    <div class="container">
                        <div class="swiper-container overflow-hidden maan-lms-categorie-slide">
                            <div class="row align-items-center">
                                <div class="col-lg-6">
                                    <div class="lms-section-title">
                                        <h2>Popular Categories</h2>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="popular-slide-nav">
                                        <div class="swiper-scrollbar"></div>
                                        <div class="swiper-pagination"></div>
                                        <div class="popular-slide-arrow">
                                            <div class="swiper-button-prev" id="p-prev"></div>
                                            <div class="swiper-button-next" id="p-next"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-wrapper">
                                @foreach (Category item in Model.MainLiCategory)
                                {
                                    <div class="swiper-slide">
                                        <a asp-area="" asp-controller="Courses" asp-action="AllCourses" asp-route-Id="@item.Id" class="popular-ctg-items">
                                            <span class="icons">
                                                <img src="@item.IconPath" alt="" style="width: 70px; height: 70px;">
                                            </span>
                                            <span class="content">
                                                <b>@item.Name</b>
                                                <small>@item.LiCourse.Count Courses</small>
                                            </span>
                                        </a>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Courses section -->
        <section class="maan-courses-area maan-lms-courses-section maan-section-padding pb-0">
            <div class="container-fluid g-0">
                <div class="maan-lms-courses-section-wrapper">
                    <img src="~/assets/img/new-home/shape4.png" alt="" class="shape1">
                    <img src="~/assets/img/new-home/shape5.png" alt="" class="shape2">
                    <div class="row g-0">
                        <div class="col-12">
                            <div class="courses-bg ">
                                <div class="maan-courses-section-wrapper">
                                    <div class="row">
                                        <div class="col-md-6 offset-lg-6 m-auto">
                                            <div class="section-title text-center">
                                                <h2>All Courses</h2>
                                            </div>
                                        </div>

                                        <div class="col-lg-12">
                                            <ul class="grid-filter courses-filter">
                                                <li data-filter="*"> <a class="is-checked" style="text-decoration:none !important" asp-area="" asp-action="AllCourses" asp-route-Id="@ViewBag.MainCatId">All</a></li>
                                                @foreach (Category item in Model.LiSubCategoryById)
                                                {
                                                    <li data-filter="/category"> <a class="is-checked" style="text-decoration:none !important" asp-area="" asp-action="NewCourses" asp-route-Id="@item.Id">@item.Name</a></li>
                                                }
                                            </ul>
                                        </div>

                                    </div>
                                    <div class="row grid-active">
                                        @foreach (Course item in Model.LiCourse)
                                        {
                                            <div class="col-lg-3 col-sm-6 grid-item category">
                                                <div class="maan-course-item">
                                                    <div class="maan-course-img">
                                                        <a asp-area="" asp-controller="CourseDetails" asp-action="Course_Details" asp-route-Id="@item.Id">
                                                            <img src="@item.ImagePath" alt="Image">
                                                        </a>
                                                    </div>
                                                    <div class="maan-course-content">
                                                        <div class="maan-course-title">
                                                            <a asp-area="" asp-controller="CourseDetails" asp-action="Course_Details" asp-route-Id="@item.Id">@item.Name</a>
                                                        </div>
                                                        <div class="maan-course-author-name">
                                                            <span>By:</span>
                                                            @item.Instructor
                                                        </div>
                                                        <ul class="maan-course-meta">
                                                            <li><i class="far fa-clock"></i> @item.Duration</li>
                                                            <li><i class="fas fa-calendar-alt"></i> 1/4/2023</li>
                                                        </ul>
                                                        <div class="maan-course-footer">
                                                            <div class="maan-course-price">
                                                                <a asp-area="" asp-controller="CourseDetails" asp-action="Course_Details" asp-route-Id="@item.Id" class="btn btn-red btn-sm">
                                                                    View
                                                                    Details
                                                                </a>

                                                            </div>
                                                            <div class="maan-course-price">
                                                                <a asp-area="" asp-controller="RegisterEnroll" asp-action="Enroll" asp-route-Id="@item.Id" class="btn btn-red btn-sm">
                                                                    Enroll Now
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Courses section -->
        <br>
        <section class="maan-cta-two-area">
            <div class="container">
                <div class="row">
                    <div class="col-12" data-cue="slideInUp">
                        <div class="maan-cta-wrapper" data-background="assets/img/bg/cta-bg2.svg">
                            <div class="cta-content">
                                <h2>Are you interested in sharing your course?</h2>
                                <a asp-area="" asp-controller="RegisterEnroll" asp-action="Enroll" class="btn btn-red btn-lg">Join Now</a>
                            </div>
                            <img src="~/assets/img/svg/star-1.svg" alt="SVG" class="shape">
                            <img src="~/assets/img/svg/star-2.svg" alt="SVG" class="shape2">
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- CTA Two Section -->
    </main>
}